security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            #provider: users_in_memory
            provider: in_database
            form_login:
                login_path: account_login
                check_path: account_login
            logout:
                path: /logout
                target: /
#                success_handler: App\Service\Logout

    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
