security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
            form_login:
                login_path: admin_login
                check_path: app_login
            logout:
                path: app_logout
        main:
            pattern: ^/
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /
            switch_user: true

    access_control:
         - { path: ^/admin/panel, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/cart/checkout, roles: IS_AUTHENTICATED_FULLY }
#         - { path: ^/, roles: ROLE_USER }
