parameters:
    from: '%env(APP_ADMIN)%'
    vat: 20

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\Cart:
        arguments:
            $vat: '%vat%'
            $from: '%from%'


    App\Service\Mailer:
        ## factory with a concrete function ##
        #factory: 'App\Factory\MailerFactory:createMailer'

        ## factory with  a static function ##
        #factory: ['App\Factory\MailerFactory', 'alertAdmins']

