
parameters:
    media: '%kernel.project_dir%/public/media'


services:
    #...
    App\Service\FileUploaderManager:
        arguments:
#            $mediaDirectory: '%media%'  <-- This line is no more used
            $logger: '@monolog.logger.request'

    _defaults:
        #...
        bind:
            $mediaDirectory: '%media%'
        autowire: true
        autoconfigure: true



    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
